services:

  tailscale-bookstack:
    image: tailscale/tailscale:latest
    container_name: tailscale-bookstack
    hostname: gappy
    environment:
      - "TS_AUTHKEY=${TAILSCALE_TOKEN}"
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - ${PWD}/serve_configs:/var/lib/serve_configs
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  bookstack:
    image: solidnerd/bookstack:22.04
    container_name: bookstack
    restart: unless-stopped         
    environment:
      DB_HOST: bookstack_db:3306 
      DB_DATABASE: bookstack 
      DB_USERNAME: bookstack
      DB_PASSWORD: secret
      APP_URL: https://gappy.tail5b1a8.ts.net
    depends_on:
      - bookstack_db
      - tailscale-bookstack
    network_mode: service:tailscale-bookstack

  bookstack_db:
    image: mysql:5.7.21
    container_name: bookstack_db
    restart: unless-stopped  # Restart container if it fails 
    environment:
      MYSQL_ROOT_PASSWORD: secret 
      MYSQL_DATABASE: bookstack  
      MYSQL_USER: bookstack    
      MYSQL_PASSWORD: secret
    volumes:
      - bookstack-db:/var/lib/mysql

volumes:
  bookstack-db:

