version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update --http-api-periodic-polls --rolling-restart chest-chest-1 reliquary-front
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=sjkfbnskjdfn8723647
    ports:
      - 8082:8080