services:
  influxdb:
      image: influxdb:2.7.1-alpine
      container_name: influxdb
      restart: always
      environment:
        - INFLUXDB_DB=influx
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=admin
      ports:
        - '127.0.0.1:8086:8086'
      volumes:
        - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data:
